# Configuração do Sistema RAG
version: "1.0"

# Configuração das ferramentas/datasources
datasources:
  - name: "cartoes_credito_outros_produtos"
    display_name: "Cartões de Crédito - Outros Produtos Bancários"
    description: "Dados sobre diversos produtos de cartão de crédito e outros produtos bancários"
    folders:
      - "Cartão de Crédito - Geral"
      - "Cartão Samsung Itaú"
      - "Extra Gold"
      - "Instituto Ayrton Senna Platinum"
      - "Itau Uniclass Mastercard Platinum"
      - "Itaú Platinum"
      - "Itaú Uniclass Black"
      - "Personnalité Black Pontos"
      - "Player_s Bank_ Conta e Cartão"
    prompt_templates:
      rag_prompt: |
        Você é um assistente especializado em cartões de crédito e produtos bancários. 
        Use as seguintes informações de contexto para responder à pergunta do usuário.
        
        Contexto:
        {context}
        
        Pergunta: {question}
        
        Sua resposta, baseada apenas no contexto fornecido:
    retriever_config:
      search_type: "mmr"  # Maximum Marginal Relevance
      top_k: 5
      fetch_k: 10
      lambda_mult: 0.5

  - name: "fidelidade_varejo"
    display_name: "Programa de Fidelidade Varejo"
    description: "Dados sobre programas de fidelidade relacionados a redes de varejo"
    folders:
      - "N Card"
      - "Passaí Gold"
      - "Pão de Açúcar Black"
      - "Pão de Açúcar Platinum"
    prompt_templates:
      rag_prompt: |
        Você é um assistente especializado em programas de fidelidade de redes de varejo. 
        Use as seguintes informações de contexto para responder à pergunta do usuário.
        
        Contexto:
        {context}
        
        Pergunta: {question}
        
        Sua resposta, baseada apenas no contexto fornecido:
    retriever_config:
      search_type: "mmr"  # Maximum Marginal Relevance
      top_k: 5
      fetch_k: 10
      lambda_mult: 0.5

  - name: "fidelidade_aereos"
    display_name: "Programas de Fidelidade Aéreos"
    description: "Dados sobre programas de fidelidade de companhias aéreas"
    folders:
      - "Azul Gold"
      - "Azul Infinite"
      - "Azul Internacional"
      - "Azul Platinum"
      - "LATAM Pass Black"
      - "LATAM Pass Gold"
      - "LATAM Pass Infinite"
      - "LATAM Pass Internacional"
      - "LATAM Pass Platinum"
    prompt_templates:
      rag_prompt: |
        Você é um assistente especializado em programas de fidelidade e milhagem de companhias aéreas. 
        Use as seguintes informações de contexto para responder à pergunta do usuário.
        
        Contexto:
        {context}
        
        Pergunta: {question}
        
        Sua resposta, baseada apenas no contexto fornecido:
    retriever_config:
      search_type: "mmr"  # Maximum Marginal Relevance
      top_k: 5
      fetch_k: 10
      lambda_mult: 0.5

# Configurações globais de prompts
global_prompts:
  # Prompt para o roteador de consultas
  router_prompt: |
    Você é um especialista em rotas de consultas para um sistema de atendimento bancário.
    Com base na consulta do usuário, determine qual fonte de dados seria mais 
    relevante para responder à pergunta:
    - 'cartoes_credito_outros_produtos': para perguntas sobre cartões diversos do Itaú, incluindo cartões premium, cartões de marca (Samsung, Extra, etc.)
    - 'fidelidade_varejo': para perguntas sobre programas de fidelidade relacionados a supermercados e varejo (N Card, Passaí, Pão de Açúcar)
    - 'fidelidade_aereos': para perguntas sobre programas de fidelidade e milhagem de companhias aéreas (Azul, LATAM)

  # Prompt para avaliação dos documentos recuperados
  grader_prompt: |
    Você é um avaliador que analisa a relevância de um documento recuperado para 
    a pergunta do usuário. Se o documento contiver palavras-chave ou significado 
    semântico remotamente relacionado à pergunta do usuário, classifique-o como relevante. 
    Não precisa ser um teste rigoroso. O objetivo é filtrar recuperações completamente irrelevantes. 
    Dê uma pontuação binária 'yes' ou 'no' para indicar se o documento é remotamente relevante 
    para a pergunta.

  fallback_prompt: |
    Você é um assistente bancário prestativo. O usuário fez uma pergunta, mas os documentos
    recuperados não foram relevantes ou úteis para respondê-la.
    Por favor, forneça uma resposta educada informando que você não conseguiu encontrar 
    informações específicas na base de conhecimento para esta pergunta.
    Evite inventar informações. Você pode oferecer assistência geral, se apropriado.

  # Novo prompt para reescrita de query
  rewrite_query_prompt: |
    Você é um especialista em reescrever consultas para melhorar a recuperação de informações.
    Sua tarefa é analisar a pergunta original do usuário e reescrevê-la em 1-3 variações mais eficazes
    que possam resultar em recuperações de documentos mais relevantes.
    
    Considere as seguintes estratégias:
    1. Use termos mais específicos ou sinônimos relevantes
    2. Decomponha perguntas complexas em consultas mais simples e direcionadas
    3. Reformule a pergunta para capturar diferentes aspectos ou perspectivas
    4. Adicione termos que possam estar presentes em documentos relevantes
    
    Formate sua resposta como uma lista numerada APENAS com as consultas reescritas, sem explicações.
    Cada consulta deve estar em uma linha separada, numerada de 1 a 3.
    
    Por exemplo:
    1. [primeira consulta reescrita]
    2. [segunda consulta reescrita]
    3. [terceira consulta reescrita]
    
    Forneça apenas consultas que provavelmente resultarão em diferentes conjuntos de documentos.
    Se a pergunta original já for clara e específica, você pode retornar menos consultas.

# Configurações de embeddings e vectorstore
embedding_config:
  provider: "huggingface"
  model: "PORTULAN/serafim-900m-portuguese-pt-sentence-encoder-ir"

vectorstore_config:
  provider: "chroma"
  persist_directory: "./chroma_db"

# Configurações do LLM
llm_config:
  model: "o3-mini-2025-01-31"
  # temperature: 0.0

# Configurações de chunking
text_splitter:
  chunk_size: 256
  chunk_overlap: 64